In [1]:
import pandas as pd

In [2]:
q1 = pd.read_csv('../data/Q1/max_spx_options_filtered_2023-01-04.csv')
q2 = pd.read_csv('../data/Q2/max_spx_options_filtered_2023-06-30.csv')
q3 = pd.read_csv('../data/Q3/max_spx_options_filtered_2023-08-15.csv')
q4 = pd.read_csv('../data/Q4/max_spx_options_filtered_2023-11-14.csv')
print(q1.shape)
print(q2.shape)
print(q3.shape)
print(q4.shape)

(9940, 22)
(10272, 22)
(10104, 22)
(10387, 22)

In [3]:
print("Q1 columns: ")
for i, col in enumerate(q1.columns, start=1):
    print(f"{i}. {col}")

Q1 columns:
1. quote_unixtime
2. quote_readtime
3. quote_date
4. quote_time_hours
5. underlying_last
6. expire_date
7. expire_unixtime
8. dte
9. option_type
10. strike
11. bid
12. ask
13. last
14. iv
15. volume
16. delta
17. gamma
18. vega
19. theta
20. rho
21. strike_distance
22. strike_distance_pct

In [4]:
q1.head()

,quote_unixtime,quote_readtime,quote_date,quote_time_hours,underlying_last,expire_date,expire_unixtime,dte,option_type,strike,...,last,iv,volume,delta,gamma,vega,theta,rho,strike_distance,strike_distance_pct
0,1672866000,2023-01-04 16:00,2023-01-04,16,3853.39,2023-01-05,1672952400,1.0,call,3500,...,305.36,0.78696,3.0,0.94780,0.00019,0.25136,-0.86006,0.03188,353.4,0.092
1,1672866000,2023-01-04 16:00,2023-01-04,16,3853.39,2023-01-05,1672952400,1.0,call,3510,...,0.00,0.76445,0.0,0.94849,0.00013,0.25093,-0.86032,0.03212,343.4,0.089
2,1672866000,2023-01-04 16:00,2023-01-04,16,3853.39,2023-01-05,1672952400,1.0,put,3550,...,0.05,0.42057,918.0,-0.00211,0.00001,0.01896,-0.07490,-0.00001,303.4,0.079
3,1672866000,2023-01-04 16:00,2023-01-04,16,3853.39,2023-01-05,1672952400,1.0,put,3560,...,0.07,0.40672,24.0,-0.00235,0.00007,0.01989,-0.07460,-0.00063,293.4,0.076
4,1672866000,2023-01-04 16:00,2023-01-04,16,3853.39,2023-01-05,1672952400,1.0,put,3570,...,0.05,0.39404,13.0,-0.00252,0.00003,0.01993,-0.07542,-0.00018,283.4,0.074

In [5]:
q1.isna().sum()

quote_unixtime         0
quote_readtime         0
quote_date             0
quote_time_hours       0
underlying_last        0
expire_date            0
expire_unixtime        0
dte                    0
option_type            0
strike                 0
bid                    0
ask                    0
last                   0
iv                     0
volume                 0
delta                  0
gamma                  0
vega                   0
theta                  0
rho                    0
strike_distance        0
strike_distance_pct    0
dtype: int64

In [6]:
print("Q1: ", list(q1.columns))
print("Q2: ", list(q2.columns))
print("Q3: ", list(q3.columns))
print("Q4: ", list(q4.columns))

Q1:  ['quote_unixtime', 'quote_readtime', 'quote_date', 'quote_time_hours', 'underlying_last', 'expire_date', 'expire_unixtime', 'dte', 'option_type', 'strike', 'bid', 'ask', 'last', 'iv', 'volume', 'delta', 'gamma', 'vega', 'theta', 'rho', 'strike_distance', 'strike_distance_pct']
Q2:  ['quote_unixtime', 'quote_readtime', 'quote_date', 'quote_time_hours', 'underlying_last', 'expire_date', 'expire_unixtime', 'dte', 'option_type', 'strike', 'bid', 'ask', 'last', 'iv', 'volume', 'delta', 'gamma', 'vega', 'theta', 'rho', 'strike_distance', 'strike_distance_pct']
Q3:  ['quote_unixtime', 'quote_readtime', 'quote_date', 'quote_time_hours', 'underlying_last', 'expire_date', 'expire_unixtime', 'dte', 'option_type', 'strike', 'bid', 'ask', 'last', 'iv', 'volume', 'delta', 'gamma', 'vega', 'theta', 'rho', 'strike_distance', 'strike_distance_pct']
Q4:  ['quote_unixtime', 'quote_readtime', 'quote_date', 'quote_time_hours', 'underlying_last', 'expire_date', 'expire_unixtime', 'dte', 'option_type', 'strike', 'bid', 'ask', 'last', 'iv', 'volume', 'delta', 'gamma', 'vega', 'theta', 'rho', 'strike_distance', 'strike_distance_pct']

In [7]:
print("Q1 vs Q2:", list(q1.columns) == list(q2.columns))
print("Q1 vs Q3:", list(q1.columns) == list(q3.columns))
print("Q1 vs Q4:", list(q1.columns) == list(q4.columns))

Q1 vs Q2: True
Q1 vs Q3: True
Q1 vs Q4: True

In [8]:
all_data = pd.concat([q1, q2, q3, q4], ignore_index=True)
print("Combined shape: ", all_data.shape)

Combined shape:  (40703, 22)

In [9]:
q1["quarter"] = "Q1"
q2["quarter"] = "Q2"
q3["quarter"] = "Q3"
q4["quarter"] = "Q4"

all_data = pd.concat([q1, q2, q3, q4], ignore_index=True)

print(all_data.shape)

(40703, 23)

In [10]:
expiry_counts = all_data["expire_date"].value_counts()

expiry_counts_df = (
    expiry_counts
    .rename_axis("expire_date")
    .reset_index(name="option_count")
)

expiry_counts_df.head(20)

expiry_counts_df.head(20)

   expire_date  option_count
0   2023-11-17          1243
1   2023-12-29          1225
2   2023-09-29          1204
3   2023-12-15          1189
4   2023-09-15          1085
5   2023-08-18           996
6   2023-08-31           966
7   2023-10-20           959
8   2023-11-30           938
9   2024-01-19           846
10  2024-03-28           772
11  2023-10-31           771
12  2024-01-31           706
13  2024-02-16           641
14  2023-07-21           609
15  2024-03-15           565
16  2024-04-19           565
17  2023-03-31           541
18  2023-07-31           486
19  2023-02-28           484

In [11]:
top_term = expiry_counts_df.iloc[0]

print("Term with most options: ")
print("Expiry:", top_term["expire_date"])
print("Number of options:", top_term["option_count"])

Term with most options:
Expiry: 2023-11-17
Number of options: 1243

In [12]:
all_data[all_data["expire_date"] == top_term["expire_date"]].head(20)
all_data[all_data["expire_date"] == top_term["expire_date"]].shape
all_data[all_data["expire_date"] == top_term["expire_date"]]["quarter"].value_counts()
all_data[all_data["expire_date"] == top_term["expire_date"]]["option_type"].value_counts()

option_type
put     629
call    614
Name: count, dtype: int64

In [13]:
selected_term = all_data[all_data["expire_date"] == top_term["expire_date"]]
selected_term[["dte"]].describe()

selected_term[["expire_date", "dte"]].head(20)

     expire_date    dte
9561  2023-11-17  317.0
9562  2023-11-17  317.0
9563  2023-11-17  317.0
9564  2023-11-17  317.0
9565  2023-11-17  317.0
9566  2023-11-17  317.0
9567  2023-11-17  317.0
9568  2023-11-17  317.0
9569  2023-11-17  317.0
9570  2023-11-17  317.0
9571  2023-11-17  317.0
9572  2023-11-17  317.0
9573  2023-11-17  317.0
9574  2023-11-17  317.0
9575  2023-11-17  317.0
9576  2023-11-17  317.0
9577  2023-11-17  317.0
9578  2023-11-17  317.0
9579  2023-11-17  317.0
9580  2023-11-17  317.0

In [14]:
import os

os.makedirs("../results", exist_ok=True)
expiry_counts_df.to_csv(
    "../results/expiry_counts.csv",
    index=False
)
print("Saved: results/expiry_counts.csv")

Saved: results/expiry_counts.csv

In [15]:
selected_term.to_csv(
    "../results/selected_term.csv",
    index=False
)
print("Saved: results/selected_term_options.csv")

Saved: results/selected_term_options.csv

In [16]:
summary = pd.DataFrame({
    "metric": ["Total observations", "Number of unique expiry terms", "Selected expiry", "Number of options for selected expiry"],
    "value": [len(all_data), all_data["expire_date"].nunique(), top_term["expire_date"], top_term["option_count"]]
})
summary

                                  metric       value
0                     Total observations       40703
1          Number of unique expiry terms         132
2                        Selected expiry  2023-11-17
3  Number of options for selected expiry        1243

In [17]:

selected_term["quote_date"].value_counts().sort_index()
selected_term.groupby("quote_date")["dte"].first()

quote_date
2023-01-04    317.00
2023-06-30    140.04
2023-08-15     94.04
2023-11-14      3.00
Name: dte, dtype: float64

In [18]:
selected_term[
    ["quote_date", "expire_date", "dte"]
].drop_duplicates().sort_values("quote_date")

       quote_date expire_date     dte
9561   2023-01-04  2023-11-17  317.00
18280  2023-06-30  2023-11-17  140.04
27262  2023-08-15  2023-11-17   94.04
30700  2023-11-14  2023-11-17    3.00

In [19]:
cme_dates = (
    selected_term[
    ["quote_date", "expire_date", "underlying_last", "dte"]
].drop_duplicates().sort_values("quote_date").reset_index(drop=True)
)
cme_dates["cme_contract"] = "SR1X3" 
cme_dates

   quote_date expire_date  underlying_last     dte cme_contract
0  2023-01-04  2023-11-17          3853.39  317.00        SR1X3
1  2023-06-30  2023-11-17          4450.23  140.04        SR1X3
2  2023-08-15  2023-11-17          4438.11   94.04        SR1X3
3  2023-11-14  2023-11-17          4496.43    3.00        SR1X3

In [20]:
cme_rates = pd.DataFrame({
    "quote_date": [
        "2023-01-04",
        "2023-06-30",
        "2023-08-15",
        "2023-11-14"
    ],
    "expire_date": [
        "2023-11-17",
        "2023-11-17",
        "2023-11-17",
        "2023-11-17"
    ],
    "cme_contract": [
        "SR1X3",
        "SR1X3",
        "SR1X3",
        "SR1X3"
    ],
    "settlement":[
        95.255,
        94.595,
        94.590,
        94.685
    ]
})
cme_rates["cme_rates_pct"] = 100 - cme_rates["settlement"]
cme_rates

   quote_date expire_date cme_contract  settlement  cme_rates_pct
0  2023-01-04  2023-11-17        SR1X3      95.255          4.745
1  2023-06-30  2023-11-17        SR1X3      94.595          5.405
2  2023-08-15  2023-11-17        SR1X3      94.590          5.410
3  2023-11-14  2023-11-17        SR1X3      94.685          5.315

In [21]:
os.makedirs("../results", exist_ok=True)
cme_rates.to_csv(
    "../results/cme_rates.csv",
    index=False
)
print("CME rates saved successfully.")

CME rates saved successfully.

In [22]:
selected_term_with_cme = selected_term.merge(
    cme_rates[["quote_date", "cme_contract","settlement", "cme_rates_pct"]],
    on="quote_date",
    how="left"
)   
selected_term_with_cme.head()

,quote_unixtime,quote_readtime,quote_date,quote_time_hours,underlying_last,expire_date,expire_unixtime,dte,option_type,strike,...,gamma,vega,theta,rho,strike_distance,strike_distance_pct,quarter,cme_contract,settlement,cme_rates_pct
0,1672866000,2023-01-04 16:00,2023-01-04,16,3853.39,2023-11-17,1700254800,317.0,call,2900,...,0.00016,5.16730,-0.44342,21.33331,953.4,0.247,Q1,SR1X3,95.255,4.745
1,1672866000,2023-01-04 16:00,2023-01-04,16,3853.39,2023-11-17,1700254800,317.0,put,2900,...,0.00019,6.42804,-0.25854,-3.71376,953.4,0.247,Q1,SR1X3,95.255,4.745
2,1672866000,2023-01-04 16:00,2023-01-04,16,3853.39,2023-11-17,1700254800,317.0,call,2925,...,0.00018,5.48073,-0.45766,21.30085,928.4,0.241,Q1,SR1X3,95.255,4.745
3,1672866000,2023-01-04 16:00,2023-01-04,16,3853.39,2023-11-17,1700254800,317.0,put,2925,...,0.00017,6.62119,-0.26339,-3.86079,928.4,0.241,Q1,SR1X3,95.255,4.745
4,1672866000,2023-01-04 16:00,2023-01-04,16,3853.39,2023-11-17,1700254800,317.0,call,2950,...,0.00020,5.61855,-0.46177,21.40863,903.4,0.234,Q1,SR1X3,95.255,4.745

In [23]:
selected_term_with_cme[
    ["quote_date", "expire_date", "cme_contract", "settlement", "cme_rates_pct"]
].drop_duplicates().sort_values("quote_date")

     quote_date expire_date cme_contract  settlement  cme_rates_pct
0    2023-01-04  2023-11-17        SR1X3      95.255          4.745
131  2023-06-30  2023-11-17        SR1X3      94.595          5.405
448  2023-08-15  2023-11-17        SR1X3      94.590          5.410
855  2023-11-14  2023-11-17        SR1X3      94.685          5.315

In [24]:
selected_term_with_cme.to_csv(
    "../results/selected_term_with_cme.csv",
    index=False
)
print("Combined SPX and Cme date saved successfully.")

Combined SPX and Cme date saved successfully.